In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv('pokemon.csv')

In [17]:
df.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [5]:
#Quantos missings hÃ¡ nas colunas
df.isna().sum()

abilities              0
against_bug            0
against_dark           0
against_dragon         0
against_electric       0
against_fairy          0
against_fight          0
against_fire           0
against_flying         0
against_ghost          0
against_grass          0
against_ground         0
against_ice            0
against_normal         0
against_poison         0
against_psychic        0
against_rock           0
against_steel          0
against_water          0
attack                 0
base_egg_steps         0
base_happiness         0
base_total             0
capture_rate           0
classfication          0
defense                0
experience_growth      0
height_m              20
hp                     0
japanese_name          0
name                   0
percentage_male       98
pokedex_number         0
sp_attack              0
sp_defense             0
speed                  0
type1                  0
type2                384
weight_kg             20
generation             0
is_legendary           0
dtype: int64

In [6]:
#tipos das colunas
df.dtypes

abilities             object
against_bug          float64
against_dark         float64
against_dragon       float64
against_electric     float64
against_fairy        float64
against_fight        float64
against_fire         float64
against_flying       float64
against_ghost        float64
against_grass        float64
against_ground       float64
against_ice          float64
against_normal       float64
against_poison       float64
against_psychic      float64
against_rock         float64
against_steel        float64
against_water        float64
attack                 int64
base_egg_steps         int64
base_happiness         int64
base_total             int64
capture_rate          object
classfication         object
defense                int64
experience_growth      int64
height_m             float64
hp                     int64
japanese_name         object
name                  object
percentage_male      float64
pokedex_number         int64
sp_attack              int64
sp_defense             int64
speed                  int64
type1                 object
type2                 object
weight_kg            float64
generation             int64
is_legendary           int64
dtype: object

In [7]:
df.columns.tolist() #exportar nome das colunas para usar nos codigos

['abilities',
 'against_bug',
 'against_dark',
 'against_dragon',
 'against_electric',
 'against_fairy',
 'against_fight',
 'against_fire',
 'against_flying',
 'against_ghost',
 'against_grass',
 'against_ground',
 'against_ice',
 'against_normal',
 'against_poison',
 'against_psychic',
 'against_rock',
 'against_steel',
 'against_water',
 'attack',
 'base_egg_steps',
 'base_happiness',
 'base_total',
 'capture_rate',
 'classfication',
 'defense',
 'experience_growth',
 'height_m',
 'hp',
 'japanese_name',
 'name',
 'percentage_male',
 'pokedex_number',
 'sp_attack',
 'sp_defense',
 'speed',
 'type1',
 'type2',
 'weight_kg',
 'generation',
 'is_legendary']

In [9]:
# Conta a quantidade de valores Ãºnicos
pd.value_counts(df['type1'])

water       114
normal      105
grass        78
bug          72
psychic      53
fire         52
rock         45
electric     39
ground       32
poison       32
dark         29
fighting     28
ghost        27
dragon       27
steel        24
ice          23
fairy        18
flying        3
Name: type1, dtype: int64

In [11]:
# Consulta pokemon de tipo fogo com ataque especial maior que 140
df.loc[(df['type1']=='fire') & (df['sp_attack'] > 140)]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
5,"['Blaze', 'Solar Power']",0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,...,88.1,6,159,115,100,fire,flying,90.5,1,0
322,"['Magma Armor', 'Solid Rock', 'Anger Point']",0.50,1.0,1.0,0.0,0.5,1.0,0.5,1.0,1.0,...,50.0,323,145,105,20,fire,ground,220.0,3,0

In [12]:
df.loc[0:4,'sp_attack':'speed'] #consultando da linha 0 atÃ© 4 e da coluna sp_attack ate speed

   sp_attack  sp_defense  speed
0         65          65     45
1         80          80     60
2        122         120     80
3         60          50     65
4         80          65     80

In [13]:
df.loc[[0, 3], ['sp_attack', 'speed']] #consultando por uma lista de linhas e colunas

   sp_attack  speed
0         65     45
3         60     65

In [27]:
#Consulta por critÃ©rios
criterio1 = df.sp_attack > 120
criterio2= df.type1 == 'water'
criterio3= df.generation == 3
df[criterio1 & criterio2 & criterio3]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
381,['Drizzle'],1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,NaN,382,180,160,90,water,NaN,352.0,3,1

In [28]:
#Obter os valores unicos de uma coluna
df['type1'].unique()

array(['grass', 'fire', 'water', 'bug', 'normal', 'poison', 'electric',
       'ground', 'fairy', 'fighting', 'psychic', 'rock', 'ghost', 'ice',
       'dragon', 'dark', 'steel', 'flying'], dtype=object)

In [29]:
#Filtrar valores por condicoes em uma lista
df[df.type1.isin(['poison','steel'])]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
22,"['Intimidate', 'Shed Skin', 'Unnerve']",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,50.0,23,40,54,55,poison,NaN,6.9,1,0
23,"['Intimidate', 'Shed Skin', 'Unnerve']",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,50.0,24,65,79,80,poison,NaN,65.0,1,0
28,"['Poison Point', 'Rivalry', 'Hustle']",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,0.0,29,40,40,41,poison,NaN,7.0,1,0
29,"['Poison Point', 'Rivalry', 'Hustle']",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,0.0,30,55,55,56,poison,NaN,20.0,1,0
30,"['Poison Point', 'Rivalry', 'Sheer Force']",0.50,1.0,1.0,0.0,0.50,0.50,1.0,1.00,1.0,...,0.0,31,75,85,76,poison,ground,60.0,1,0
31,"['Poison Point', 'Rivalry', 'Hustle']",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,100.0,32,40,40,50,poison,NaN,9.0,1,0
32,"['Poison Point', 'Rivalry', 'Hustle']",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,100.0,33,55,55,65,poison,NaN,19.5,1,0
33,"['Poison Point', 'Rivalry', 'Sheer Force']",0.50,1.0,1.0,0.0,0.50,0.50,1.0,1.00,1.0,...,100.0,34,85,75,85,poison,ground,62.0,1,0
40,"['Inner Focus', 'Infiltrator']",0.25,1.0,1.0,2.0,0.50,0.25,1.0,1.00,1.0,...,50.0,41,30,40,55,poison,flying,7.5,1,0
41,"['Inner Focus', 'Infiltrator']",0.25,1.0,1.0,2.0,0.50,0.25,1.0,1.00,1.0,...,50.0,42,65,75,90,poison,flying,55.0,1,0
87,"['Stench', 'Sticky Hold', 'Poison Touch', 'Poi...",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,50.0,88,40,50,25,poison,poison,NaN,1,0
88,"['Stench', 'Sticky Hold', 'Poison Touch', 'Poi...",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,50.0,89,65,100,50,poison,poison,NaN,1,0
108,['Levitate'],0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,50.0,109,60,45,35,poison,NaN,1.0,1,0
109,['Levitate'],0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,50.0,110,85,70,60,poison,NaN,9.5,1,0
168,"['Inner Focus', 'Infiltrator']",0.25,1.0,1.0,2.0,0.50,0.25,1.0,1.00,1.0,...,50.0,169,70,80,130,poison,flying,75.0,2,0
207,"['Rock Head', 'Sturdy', 'Sheer Force']",0.50,1.0,0.5,0.0,0.50,2.00,2.0,0.50,1.0,...,50.0,208,55,95,30,steel,ground,400.0,2,0
226,"['Keen Eye', 'Sturdy', 'Weak Armor']",0.25,1.0,0.5,2.0,0.50,1.00,2.0,0.50,1.0,...,50.0,227,40,70,70,steel,flying,50.5,2,0
302,"['Hyper Cutter', 'Intimidate', 'Sheer Force']",0.25,0.5,0.0,1.0,0.50,1.00,2.0,0.50,1.0,...,50.0,303,55,95,50,steel,fairy,11.5,3,0
303,"['Sturdy', 'Rock Head', 'Heavy Metal']",0.50,1.0,0.5,1.0,0.50,4.00,1.0,0.25,1.0,...,50.0,304,40,40,30,steel,rock,60.0,3,0
304,"['Sturdy', 'Rock Head', 'Heavy Metal']",0.50,1.0,0.5,1.0,0.50,4.00,1.0,0.25,1.0,...,50.0,305,50,50,40,steel,rock,120.0,3,0
305,"['Sturdy', 'Rock Head', 'Heavy Metal']",0.50,1.0,0.5,1.0,0.50,4.00,1.0,0.25,1.0,...,50.0,306,60,80,50,steel,rock,360.0,3,0
315,"['Liquid Ooze', 'Sticky Hold', 'Gluttony']",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,50.0,316,43,53,40,poison,NaN,10.3,3,0
316,"['Liquid Ooze', 'Sticky Hold', 'Gluttony']",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,50.0,317,73,83,55,poison,NaN,80.0,3,0
335,"['Shed Skin', 'Infiltrator']",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,50.0,336,100,60,65,poison,NaN,52.5,3,0
373,"['Clear Body', 'Light Metal']",1.00,2.0,0.5,1.0,0.50,1.00,2.0,0.50,2.0,...,NaN,374,35,60,30,steel,psychic,95.2,3,0
374,"['Clear Body', 'Light Metal']",1.00,2.0,0.5,1.0,0.50,1.00,2.0,0.50,2.0,...,NaN,375,55,80,50,steel,psychic,202.5,3,0
375,"['Clear Body', 'Light Metal']",1.00,2.0,0.5,1.0,0.50,1.00,2.0,0.50,2.0,...,NaN,376,105,110,110,steel,psychic,550.0,3,0
378,"['Clear Body', 'Light Metal']",0.50,1.0,0.5,1.0,0.50,2.00,2.0,0.50,1.0,...,NaN,379,75,150,50,steel,NaN,205.0,3,1
384,['Serene Grace'],1.00,2.0,0.5,1.0,0.50,1.00,2.0,0.50,2.0,...,NaN,385,100,100,100,steel,psychic,1.1,3,1
433,"['Stench', 'Aftermath', 'Keen Eye']",1.00,0.5,1.0,1.0,1.00,1.00,1.0,1.00,0.5,...,50.0,434,41,41,74,poison,dark,19.2,4,0
434,"['Stench', 'Aftermath', 'Keen Eye']",1.00,0.5,1.0,1.0,1.00,1.00,1.0,1.00,0.5,...,50.0,435,71,61,84,poison,dark,38.0,4,0
435,"['Levitate', 'Heatproof', 'Heavy Metal']",1.00,2.0,0.5,1.0,0.50,1.00,2.0,0.50,2.0,...,NaN,436,24,86,23,steel,psychic,60.5,4,0
436,"['Levitate', 'Heatproof', 'Heavy Metal']",1.00,2.0,0.5,1.0,0.50,1.00,2.0,0.50,2.0,...,NaN,437,79,116,33,steel,psychic,187.0,4,0
450,"['Battle Armor', 'Sniper', 'Keen Eye']",0.50,1.0,1.0,1.0,0.50,0.25,2.0,2.00,1.0,...,50.0,451,30,55,65,poison,bug,12.0,4,0
451,"['Battle Armor', 'Sniper', 'Keen Eye']",1.00,0.5,1.0,1.0,1.00,1.00,1.0,1.00,0.5,...,50.0,452,60,75,95,poison,dark,61.5,4,0
452,"['Anticipation', 'Dry Skin', 'Poison Touch']",0.25,0.5,1.0,1.0,1.00,0.50,1.0,2.00,1.0,...,50.0,453,61,40,50,poison,fighting,23.0,4,0
453,"['Anticipation', 'Dry Skin', 'Poison Touch']",0.25,0.5,1.0,1.0,1.00,0.50,1.0,2.00,1.0,...,50.0,454,86,65,85,poison,fighting,44.4,4,0
482,"['Pressure', 'Telepathy']",0.50,1.0,1.0,0.5,1.00,2.00,1.0,0.50,1.0,...,NaN,483,150,100,90,steel,dragon,683.0,4,1
567,"['Stench', 'Sticky Hold', 'Aftermath']",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,50.0,568,40,62,65,poison,NaN,31.0,5,0
568,"['Stench', 'Weak Armor', 'Aftermath']",0.50,1.0,1.0,1.0,0.50,0.50,1.0,1.00,1.0,...,50.0,569,60,82,75,poison,NaN,107.3,5,0
598,"['Plus', 'Minus', 'Clear Body']",0.50,1.0,0.5,1.0,0.50,2.00,2.0,0.50,1.0,...,NaN,599,45,60,30,steel,NaN,21.0,5,0
599,"['Plus', 'Minus', 'Clear Body']",0.50,1.0,0.5,1.0,0.50,2.00,2.0,0.50,1.0,...,NaN,600,70,85,50,steel,NaN,51.0,5,0
600,"['Plus', 'Minus', 'Clear Body']",0.50,1.0,0.5,1.0,0.50,2.00,2.0,0.50,1.0,...,NaN,601,70,85,90,steel,NaN,81.0,5,0
637,['Justified'],0.25,0.5,0.5,1.0,1.00,2.00,2.0,1.00,1.0,...,NaN,638,90,72,108,steel,fighting,250.0,5,1
678,['No Guard'],0.25,2.0,0.5,1.0,0.50,0.00,2.0,0.50,2.0,...,50.0,679,35,37,28,steel,ghost,2.0,6,0
679,['No Guard'],0.25,2.0,0.5,1.0,0.50,0.00,2.0,0.50,2.0,...,50.0,680,45,49,35,steel,ghost,4.5,6,0
680,['Stance Change'],0.25,2.0,0.5,1.0,0.50,0.00,2.0,0.50,2.0,...,50.0,681,150,50,60,steel,ghost,53.0,6,0
689,"['Poison Point', 'Poison Touch', 'Adaptability']",0.50,1.0,1.0,2.0,0.50,0.50,0.5,1.00,1.0,...,50.0,690,60,60,30,poison,water,7.3,6,0
690,"['Poison Point', 'Poison Touch', 'Adaptability']",0.50,1.0,2.0,0.5,1.00,0.50,0.5,1.00,1.0,...,50.0,691,97,123,44,poison,dragon,81.5,6,0
706,"['Prankster', 'Magician']",0.25,0.5,0.0,1.0,0.50,1.00,2.0,0.50,1.0,...,50.0,707,80,87,75,steel,fairy,3.0,6,0
746,"['Merciless', 'Limber', 'Regenerator']",0.50,1.0,1.0,2.0,0.50,0.50,0.5,1.00,1.0,...,50.0,747,43,52,45,poison,water,8.0,7,0
747,"['Merciless', 'Limber', 'Regenerator']",0.50,1.0,1.0,2.0,0.50,0.50,0.5,1.00,1.0,...,50.0,748,53,142,35,poison,water,14.5,7,0
756,"['Corrosion', 'Oblivious']",0.25,1.0,1.0,1.0,0.25,0.50,0.5,1.00,1.0,...,88.1,757,71,40,77,poison,fire,4.8,7,0
757,"['Corrosion', 'Oblivious']",0.25,1.0,1.0,1.0,0.25,0.50,0.5,1.00,1.0,...,0.0,758,111,60,117,poison,fire,22.2,7,0
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.50,1.00,2.0,0.50,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.50,1.00,2.0,0.50,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

In [38]:
#Filtrar termos/palavras dentro de uma variavel
df[df['type1'].str.contains('fly')]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
640,"['Prankster', 'Defiant', 'Regenerator']",0.5,1.0,1.0,2.0,1.0,0.5,1.0,1.0,1.0,...,100.0,641,110,90,121,flying,NaN,63.0,5,1
713,"['Frisk', 'Infiltrator', 'Telepathy']",0.5,1.0,2.0,1.0,2.0,0.5,0.5,1.0,1.0,...,50.0,714,45,40,55,flying,dragon,8.0,6,0
714,"['Frisk', 'Infiltrator', 'Telepathy']",0.5,1.0,2.0,1.0,2.0,0.5,0.5,1.0,1.0,...,50.0,715,97,80,123,flying,dragon,85.0,6,0

In [44]:
#Numero de linhas por condicao
(df.type1 == "water").sum()

114

In [41]:
#Porcentagem de linhas naquela condicao
(df.sp_attack > 130).mean()

0.05118601747815231

In [51]:
#Agregar dados por varias funcoes
df.groupby('type1').sp_attack.agg(['mean','max']) #maior e media de especial ataque por tipo

               mean  max
type1
bug       56.652778  145
dark      74.517241  140
dragon    89.592593  180
electric  87.538462  173
fairy     81.500000  131
fighting  50.107143  140
fire      87.730769  159
flying    84.000000  110
ghost     82.444444  170
grass     74.320513  145
ground    51.937500  150
ice       77.434783  130
normal    56.980952  135
poison    61.562500  111
psychic   92.603774  194
rock      63.200000  160
steel     72.708333  150
water     74.061404  180

In [18]:
#Agregar dados por varias colunas e funcoes com uma variavel numerica
df.groupby(['type1','type2']).sp_attack.agg(['mean','max']) #maior e media de especial ataque por tipo

                         mean  max
type1    type2
bug      electric   88.500000  145
         fairy      75.000000   95
         fighting   76.666667  137
         fire       92.500000  135
         flying     75.000000  116
         ghost      30.000000   30
         grass      55.666667   70
         ground     30.000000   30
         poison     42.272727   90
         rock       36.666667   65
         steel      70.600000  120
         water      43.333333   60
dark     dragon     83.000000  125
         fighting   40.000000   45
         fire      110.000000  140
         flying     84.200000  131
         ghost      85.000000   85
         ice        40.000000   45
         psychic    52.500000   68
         steel      50.000000   60
dragon   electric  120.000000  120
         fighting   82.500000  100
         fire      150.000000  150
         flying    127.500000  180
         ground     75.250000  120
         ice       170.000000  170
         psychic   150.000000  160
electric electric   95.000000   95
         fairy      88.000000   95
         flying    115.000000  145
...                       ...  ...
rock     grass      71.000000   81
         ground     45.000000   65
         ice        83.000000   99
         poison    127.000000  127
         psychic    75.000000   95
         steel      54.666667   75
         water      69.666667  115
steel    dragon    150.000000  150
         fairy      88.333333  130
         fighting   90.000000   90
         flying     73.500000  107
         ghost      76.666667  150
         ground     55.000000   55
         psychic    66.333333  105
         rock       50.000000   60
water    bug        45.000000   50
         dark      104.500000  153
         dragon    122.500000  150
         electric   66.000000   76
         fairy      75.250000  126
         fighting   99.500000  129
         flying     70.142857   95
         ghost      75.000000   85
         grass      63.333333   90
         ground     67.666667   95
         ice        80.000000   85
         poison     61.666667   80
         psychic    88.000000  130
         rock       61.500000   83
         steel     111.000000  111

[148 rows x 2 columns]

In [54]:
#Agregar os dados por multiplas colunas numericas
df.groupby('type1').agg({'speed':['mean','max'], #mÃ©dia e maximo velocidade
                         'sp_defense': ['mean','min']}) #media e minimo defesa especial

              speed      sp_defense
               mean  max       mean min
type1
bug       63.569444  160  62.513889  20
dark      75.310345  125  69.068966  30
dragon    76.111111  120  84.555556  30
electric  85.410256  150  70.051282  32
fairy     53.666667  100  87.777778  40
fighting  64.285714  118  63.428571  30
fire      73.346154  126  71.538462  40
flying    99.666667  123  70.000000  40
ghost     58.333333  130  78.296296  33
grass     59.025641  145  69.230769  30
ground    59.968750  110  62.281250  30
ice       62.739130  110  76.130435  30
normal    69.533333  135  63.200000  20
poison    64.187500  130  65.531250  40
psychic   75.150943  180  85.735849  31
rock      57.422222  150  73.377778  25
steel     56.583333  110  82.208333  37
water     63.921053  132  71.798246  20

In [19]:
#Agrupando a partir de associaÃ§ao de colunas
habilidades_tot = {'sp_attack': 'ataque', 'attack': 'ataque', 'sp_defense': 'defesa', 'defense': 'defesa'}

In [43]:
df2 = df[['name','sp_attack','attack','sp_defense','defense']]
df2.set_index('name', inplace=True)

In [44]:
df2.head()

            sp_attack  attack  sp_defense  defense
name
Bulbasaur          65      49          65       49
Ivysaur            80      62          80       63
Venusaur          122     100         120      123
Charmander         60      52          50       43
Charmeleon         80      64          65       58

In [46]:
(df2.groupby(habilidades_tot, axis=1).sum()).head()

            ataque  defesa
name
Bulbasaur      114     114
Ivysaur        142     143
Venusaur       222     243
Charmander     112      93
Charmeleon     144     123

In [60]:
#Agrupando por uma funÃ§Ã£o criada
def dif_quantil(x):
    return (x.quantile(0.9) - x.quantile(0.1))

In [62]:
df.groupby('type1')[['attack','defense']].agg(dif_quantil)

          attack  defense
type1
bug         94.5     74.7
dark        70.0     66.6
dragon      80.6     70.6
electric    67.0     50.6
fairy       57.9     46.2
fighting    63.6     50.1
fire        64.8     64.5
flying      56.0     36.0
ghost       76.0     84.8
grass       70.8     68.0
ground      73.9     75.0
ice         69.4     60.0
normal      76.0     64.6
poison      52.2     54.1
psychic     86.0     68.2
rock        88.0     98.0
steel       76.0     68.2
water       65.0     66.9

In [65]:
#Agrupando por fraÃ§Ãµes da base
faixas_peso = [0,250,500,750,1000]
grupos = pd.cut(df['weight_kg'],faixas_peso)

In [71]:
df.groupby(grupos)[['attack','sp_attack']].mean()

                 attack   sp_attack
weight_kg
(0, 250]      75.713137   70.703753
(250, 500]   121.500000   90.115385
(500, 750]   125.500000  104.750000
(750, 1000]  107.200000   87.600000

In [72]:
#Agrupando por quantil
grupos = pd.qcut(df['weight_kg'],[0, 0.2,0.5,0.8,1])

In [73]:
df.groupby(grupos)[['attack','sp_attack']].mean()

                   attack  sp_attack
weight_kg
(0.099, 7.0]    57.188679  58.710692
(7.0, 27.3]     66.663793  63.228448
(27.3, 81.9]    85.059829  79.294872
(81.9, 999.9]  103.948718  85.807692